table Medidas
	lineageTag: 67e3ae67-1f67-47a0-ad6c-347ceb96d61c

	measure Faturamento = SUM(vendas[valor])
		formatString: 0
		lineageTag: b81c7a80-b3d6-48c2-a631-46163361da93

	measure 'Qtd Vendas' =
			
			COUNTROWS(vendas)
		formatString: 0
		lineageTag: ec59589d-f1fb-49c5-a489-dc69a4fb5d81

	measure 'Ticket Médio' = DIVIDE([Faturamento],[Qtd Vendas])
		lineageTag: 45fa2b80-33fc-4458-a7a8-1e4c34470e94

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Media Vendas' = DIVIDE([Faturamento],[Qtd Vendas])
		lineageTag: 2b7e7cfa-addb-4da2-8916-5ad93c543fab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

